urls.py
from django.urls import path
from lotus.views import (
    lotus_user_list,
    lotus_user_employee_details,
    lotus_user_student_details,

    lotus_app_list,
    lotus_app_add,
    lotus_app_details,
    lotus_app_update,

    lotus_page_list,
    lotus_page_add,
    lotus_page_details,
    lotus_page_update,

    lotus_group_list,
    lotus_group_add,
    lotus_group_details,
    lotus_group_app_add,
    lotus_group_page_add,
    lotus_group_app_delete,
    

    lotus_importer,
    lotus_404,
    lotus_exception,

    lotus_employee_add,
)

urlpatterns=[
    path('lts/user/list/',lotus_user_list,name='lotus_user_list'),
    path('lts/user/employee/<int:id>/details/',lotus_user_employee_details,name='lotus_user_employee_details'),
    path('lts/user/student/<int:id>/details/',lotus_user_student_details,name='lotus_user_student_details'),


    path('lts/app/list/',lotus_app_list,name='lotus_app_list'),
    path('lts/app/add/',lotus_app_add,name='lotus_app_add'),
    path('lts/app/<int:id>/details/',lotus_app_details,name='lotus_app_details'),
    path('lts/app/<int:id>/update/',lotus_app_update,name='lotus_app_update'),
    

    path('lts/page/list/',lotus_page_list,name='lotus_page_list'),
    path('lts/page/add/',lotus_page_add,name='lotus_page_add'),
    path('lts/page/<int:id>/details/',lotus_page_details,name='lotus_page_details'),
    path('lts/page/<int:id>/update/',lotus_page_update,name='lotus_page_update'),


    path('lts/group/list/',lotus_group_list,name='lotus_group_list'),
    path('lts/group/add/',lotus_group_add,name='lotus_group_add'),
    path('lts/group/<int:id>/details/',lotus_group_details,name='lotus_group_details'),
    path('lts/group/<int:group>/app/add/',lotus_group_app_add,name='lotus_group_app_add'),
    path('lts/group/<int:group>/page/add/',lotus_group_page_add,name='lotus_group_page_add'),
    path('lts/group/<int:group>/app/<int:app>/delete/',lotus_group_app_delete,name='lotus_group_app_delete'),


    path('lts/importer/',lotus_importer,name='lotus_importer'),


    path('warning/404/<str:violation>/<str:message>/',lotus_404,name="lotus_404"),

    path('warning/exception/',lotus_exception,name="lotus_exception"),

    path('emp/add/',lotus_employee_add,name="lotus_employee_add")
]

models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db.models.signals import post_save
from django.dispatch import receiver as re
from django.utils.text import slugify

from datetime import datetime


class UserManager(BaseUserManager):
    def create_user(self, username, password=None):
        if not username:
            raise ValueError('Users must have a Username')
        
        print('creating user')
        user = self.model(
            username=username,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password=None):

        
        user = self.create_user(
            username=username,
            password=password,
        )
        user.is_staff=True
        user.is_active=True
        user.is_admin=True
        user.is_superuser=True
        user.save(using=self._db)

        
        return user


class User(AbstractBaseUser):
    username                    = models.CharField(max_length=63, blank=True, null=True, unique=True, verbose_name="Username")
    email                       = models.EmailField(max_length=225, blank=True, null=False, verbose_name="Email Field")
    is_staff                    = models.BooleanField(default=False)
    is_active                   = models.BooleanField(default=True)     
    is_admin                    = models.BooleanField(default=False)
    is_superuser                = models.BooleanField(default=False)
    init_log                    = models.BooleanField(default=True)
    is_logged                   = models.BooleanField(default=False)
    date_joined                 = models.DateTimeField(auto_now_add=True)   
    last_login                  = models.DateTimeField(auto_now=True)
    profile_pic                 = models.ImageField(null=True, blank=True)


    USERNAME_FIELD = 'username'

    objects = UserManager()

    def __str__(self):
        return self.username


class Group(models.Model):
    id              = models.IntegerField(primary_key=True)
    name            = models.CharField(max_length=225,unique=True)
    description     = models.CharField(max_length=225,blank=True,null=True)
    is_enabled      = models.BooleanField(default=False)
    created_date    = models.DateTimeField(auto_now_add = True,blank=True,null=True)
    updated_date    = models.DateTimeField(auto_now = True,blank=True,null=True)
    created_by      = models.ForeignKey(User, blank=True, null=True,on_delete=models.CASCADE, related_name="group_created_by")
    updated_by      = models.ForeignKey(User, blank=True, null=True,on_delete=models.CASCADE, related_name="group_updated_by")

    def __str__(self):
        return self.name
    
    
class App(models.Model):
    id              = models.IntegerField(primary_key=True)
    name            = models.CharField(max_length=225,unique=True)
    description     = models.CharField(max_length=225,blank=True,null=True)
    url             = models.CharField(max_length=225,blank=True,null=True)
    as_app_select   = models.BooleanField(default=False)
    sequence        = models.IntegerField(blank=True, null=True)
    icon_class      = models.CharField(max_length=225, blank=True, null=True)
    user_list       = models.CharField(max_length=225, blank=True, null=True)
    is_enabled      = models.BooleanField(default=False)
    created_date    = models.DateTimeField(auto_now_add = True,blank=True,null=True)
    updated_date    = models.DateTimeField(auto_now = True,blank=True,null=True)
    created_by      = models.ForeignKey(User, blank=True, null=True,on_delete=models.CASCADE, related_name="app_created_by")
    updated_by      = models.ForeignKey(User, blank=True, null=True,on_delete=models.CASCADE, related_name="app_updated_by")

    def __str__(self):
        return self.name
    

class Page(models.Model):
    id                  = models.IntegerField(primary_key=True)
    app                 = models.ForeignKey(App,null=True,blank=True,on_delete=models.SET_NULL)
    name                = models.CharField(max_length=225,unique=True)
    description         = models.CharField(max_length=225,blank=True,null=True)
    path                = models.CharField(max_length=225,unique=True,blank=True,null=True)
    is_enabled          = models.BooleanField(default=False)
    is_action_button    = models.BooleanField(default=False)
    created_date        = models.DateTimeField(auto_now_add = True,blank=True,null=True)
    updated_date        = models.DateTimeField(auto_now = True,blank=True,null=True)
    created_by          = models.ForeignKey(User, blank=True, null=True,on_delete=models.CASCADE, related_name="page_created_by")
    updated_by          = models.ForeignKey(User, blank=True, null=True,on_delete=models.CASCADE, related_name="page_updated_by")

    def __str__(self):
        return self.name
        




class GroupApp(models.Model):
    group=models.ForeignKey(Group, null=True,on_delete=models.SET_NULL)  
    app=models.ForeignKey(App,null=True,on_delete=models.SET_NULL)


class GroupPage(models.Model):
    group=models.ForeignKey(Group,null=True,on_delete=models.SET_NULL)  
    page=models.ForeignKey(Page,null=True,on_delete=models.SET_NULL)    


class UserGroup(models.Model):
    # id              = models.IntegerField(primary_key=True)
    user            = models.ForeignKey(User,null=True,on_delete=models.SET_NULL)
    group           = models.ForeignKey(Group,null=True,on_delete=models.SET_NULL)
    created_date    = models.DateTimeField(auto_now_add = True,blank=True,null=True)
    updated_date    = models.DateTimeField(auto_now = True,blank=True,null=True)
    created_by      = models.ForeignKey(User, blank=True, null=True,on_delete=models.CASCADE, related_name="user_group_created_by")
    updated_by      = models.ForeignKey(User, blank=True, null=True,on_delete=models.CASCADE, related_name="user_group_updated_by")

    def __str__(self):
        return f"{self.user.id} - {self.group.name}"  
    

class Gender(models.Model):
    name            = models.CharField(max_length=225,unique=True)
    description     = models.CharField(max_length=225,blank=True,null=True)
    is_enabled      = models.BooleanField(default=False)
    created_date    = models.DateTimeField(auto_now_add = True,blank=True,null=True)
    updated_date    = models.DateTimeField(auto_now = True,blank=True,null=True)
    created_by      = models.ForeignKey(User, blank=True, null=True,on_delete=models.CASCADE, related_name="gender_created_by")
    updated_by      = models.ForeignKey(User, blank=True, null=True,on_delete=models.CASCADE, related_name="gender_updated_by")

    def __str__(self):
        return self.name    
    
class ContactType(models.Model):
    name            = models.CharField(max_length=225,unique=True)
    description     = models.CharField(max_length=225,blank=True,null=True)
    is_enabled      = models.BooleanField(default=False)
    created_date    = models.DateTimeField(auto_now_add = True,blank=True,null=True)
    updated_date    = models.DateTimeField(auto_now = True,blank=True,null=True)
    created_by      = models.ForeignKey(User, blank=True, null=True,on_delete=models.CASCADE, related_name="contact_type_created_by")
    updated_by      = models.ForeignKey(User, blank=True, null=True,on_delete=models.CASCADE, related_name="contact_type_updated_by")

    def __str__(self):
        return self.name
    

class AddressType(models.Model):
    name            = models.CharField(max_length=225,unique=True)
    description     = models.CharField(max_length=225,blank=True,null=True)
    is_enabled      = models.BooleanField(default=False)
    created_date    = models.DateTimeField(auto_now_add = True,blank=True,null=True)
    updated_date    = models.DateTimeField(auto_now = True,blank=True,null=True)
    created_by      = models.ForeignKey(User, blank=True, null=True,on_delete=models.CASCADE, related_name="address_type_created_by")
    updated_by      = models.ForeignKey(User, blank=True, null=True,on_delete=models.CASCADE, related_name="address_type_updated_by")

    def __str__(self):
        return self.name
    


class FamilyRelationshipType(models.Model):
    name            = models.CharField(max_length=225,unique=True)
    description     = models.CharField(max_length=225,blank=True,null=True)
    is_enabled      = models.BooleanField(default=False)
    created_date    = models.DateTimeField(auto_now_add = True,blank=True,null=True)
    updated_date    = models.DateTimeField(auto_now = True,blank=True,null=True)
    created_by      = models.ForeignKey(User, blank=True, null=True,on_delete=models.CASCADE, related_name="lotus_family_relationship_type_created_by")
    updated_by      = models.ForeignKey(User, blank=True, null=True,on_delete=models.CASCADE, related_name="lotus_family_relationship_type_updated_by")

    def __str__(self):
        return self.name    

class BloodType(models.Model):
    name            = models.CharField(max_length=225,unique=True)
    description     = models.CharField(max_length=225,blank=True,null=True)
    is_enabled      = models.BooleanField(default=False)
    created_date    = models.DateTimeField(auto_now_add = True,blank=True,null=True)
    updated_date    = models.DateTimeField(auto_now = True,blank=True,null=True)
    created_by      = models.ForeignKey(User, blank=True, null=True,on_delete=models.CASCADE, related_name="blood_type_created_by")
    updated_by      = models.ForeignKey(User, blank=True, null=True,on_delete=models.CASCADE, related_name="blood_type_updated_by")

    def __str__(self):
        return self.name     


class Suffix(models.Model):
    name            = models.CharField(max_length=225,unique=True)
    description     = models.CharField(max_length=225,blank=True,null=True)
    is_enabled      = models.BooleanField(default=False)

templates/lotus/pages/user/lotus_user_employee_details.html
{% extends 'lotus/layout/base.html' %}
{% load static %}

{% block content %}
<section>
    <div class="container-fluid">
        <div class="lotus-card-dark mb-3">
            <div class="lotus-card-header-dark">
                User Details
            </div>
            <div class="lotus-card-body-dark">
                <div class="card-body">
                    <div class="row mt-2">
                        <div class="col-2 text-end" style="color: #aaa;">ID: </div>
                        <div class="col-10" style="color: #aaa;">{{details.id}}</div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-2 text-end" style="color: #aaa;">Name: </div>
                        <div class="col-10" style="color: #aaa;">{% if details.employee %} {{details.employee}} {% elif details.student %} {{details.student}} {% endif %}</div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-2 text-end" style="color: #aaa;">Role: </div>
                        <div class="col-10" style="color: #aaa;">{% if details.employee %} {{details.employee.role}} {% elif details.student %} {{details.student.role}} {% endif %}</div>
                    </div>
                </div>
            </div>
            <div class="lotus-card-header-dark">
                <div class="row">
                    <div class="col text-end">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section>
    <div class="container-fluid">
        <div class="lotus-card-dark mb-3">
            <div class="lotus-card-header-dark">
                Group Details
            </div>
            <form action="" method="post">{% csrf_token %}
                <div class="lotus-card-body-dark">
                    <div class="card-body">
                        <div class="row mt-2">
                            <div class="col-2 text-end" style="color: #aaa;">Current Group: </div>
                            <div class="col-10">{% for group in details.usergroup_set.all %} {{group}} {% endfor %}</div>
                        </div>
                        <div class="row mt-2">
                            <div class="col-2 text-end" style="color: #aaa;">Select New Group: </div>
                            <div class="col-10">{{user_group_form.group}}</div>
                        </div>
                        <div class="row mt-2">
                            <div class="col-2 text-end" style="color: #aaa;"></div>
                            <div class="col-10" style="color: #aaa;"><button class="btn btn-sm btn-secondary py-0" type="submit">Update</button></div>
                        </div>
                    </div>
                </div>
            </form>
            <div class="lotus-card-header-dark">
                <div class="row">
                    <div class="col text-end">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section>
    <div class="container-fluid">
        <div class="lotus-card-dark mb-3">
            <div class="lotus-card-header-dark">
                Group Application List
            </div>
            <div class="lotus-card-body-dark">
                <div class="card-body">
                    {% for apps in group_apps %}
                        {{apps.app.name}}
                    {% endfor %}
                </div>
            </div>
            <div class="lotus-card-header-dark">
                <div class="row">
                    <div class="col text-end">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section>
    <div class="container-fluid">
        <div class="lotus-card-dark mb-3">
            <div class="lotus-card-header-dark">
                Group Page List
            </div>
            <div class="lotus-card-body-dark">
                <div class="card-body">
                    {% for pages in group_pages %}
                        {{pages.page.name}}
                    {% endfor %}
                </div>
            </div>
            <div class="lotus-card-header-dark">
                <div class="row">
                    <div class="col text-end">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock content %}

templates/lotus/pages/user/lotus_user_list copy.html
{% extends 'lotus/layout/base.html' %}
{% load static %}

{% block content %}
<section>
    <div class="container-fluid">
        <div class="lotus-card-dark mb-3">
            <div class="lotus-card-header-dark">
                <div class="row">
                    <div class="col">Employee User List</div>
                    <div class="col"> <a href="{% url 'lotus_employee_add' %}" role="button">Add Emplopyee</a> </div>
                </div>
            </div>
            <div class="lotus-card-body-dark">
                <table>
                    <thead>
                        <tr>
                            <th style="width: 63px; border: 1px solid #636363;">ID</th>
                            <th style="width: 270px; border: 1px solid #636363;">Username</th>
                            <th style="width: 270px; border: 1px solid #636363;">Role</th>
                            <th style="width: 270px; border: 1px solid #636363;">Group</th>
                            <th style="width: 270px; border: 1px solid #636363;">Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for ea in employee_list %}
                            {% if ea.employee %} 
                                <tr>
                                    <td style="border: 1px solid #636363;"><a href="{% url 'lotus_user_employee_details' ea.id %}" style="color: #aaa;">{{ ea.id }}</a></td>
                                    <td style="border: 1px solid #636363;">{{ ea.username }}</td>
                                    <td style="border: 1px solid #636363;">{{ea.employee.role}}</td>
                                    <td style="border: 1px solid #636363;">{{ea.usergroup_set}}</td>
                                    <td style="border: 1px solid #636363;">{{ea.employee}}</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container-fluid">
        <div class="lotus-card-dark mb-3">
            <div class="lotus-card-header-dark">
                Student User List
            </div>
            <div class="lotus-card-body-dark">
                <table>
                    <thead>
                        <tr>
                            <th style="width: 63px; border: 1px solid #636363;">ID</th>
                            <th style="width: 270px; border: 1px solid #636363;">Username</th>
                            <th style="width: 270px; border: 1px solid #636363;">Role</th>
                            <th style="width: 270px; border: 1px solid #636363;">Group</th>
                            <th style="width: 270px; border: 1px solid #636363;">Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for ea in student_list %}
                            {% if ea.student %} 
                                <tr>
                                    <td style="border: 1px solid #636363;"><a href="{% url 'lotus_user_student_details' ea.id %}" style="color: #aaa;">{{ ea.id }}</a></td>
                                    <td style="border: 1px solid #636363;">{{ ea.username }}</td>
                                    <td style="border: 1px solid #636363;">{{ea.student.role}}</td>
                                    <td style="border: 1px solid #636363;">{{ea.usergroup_set}}</td>
                                    <td style="border: 1px solid #636363;">{{ea.student}}</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>







{% endblock content %}

templates/lotus/pages/user/lotus_user_list.html
{% extends 'lotus/layout/base.html' %}
{% load static %}

{% block content %}
<section>
    <div class="container-fluid">
        <div class="lotus-card-dark mb-3">
            <div class="lotus-card-header-dark">
                Employee User List
            </div>
            <div class="lotus-card-body-dark">
                <table>
                    <thead>
                        <tr>
                            <th style="width: 63px; border: 1px solid #636363;">ID</th>
                            <th style="width: 270px; border: 1px solid #636363;">Username</th>
                            <th style="width: 270px; border: 1px solid #636363;">Role</th>
                            <th style="width: 270px; border: 1px solid #636363;">Group</th>
                            <th style="width: 270px; border: 1px solid #636363;">Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for ea in employee_list %}
                            {% if ea.employee %} 
                                <tr>
                                    <td style="border: 1px solid #636363;"><a href="{% url 'lotus_user_employee_details' ea.id %}" style="color: #aaa;">{{ ea.id }}</a></td>
                                    <td style="border: 1px solid #636363;">{{ ea.username }}</td>
                                    <td style="border: 1px solid #636363;">{{ea.employee.role}}</td>
                                    <td style="border: 1px solid #636363;">{{ea.usergroup_set}}</td>
                                    <td style="border: 1px solid #636363;">{{ea.employee}}</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container-fluid">
        <div class="lotus-card-dark mb-3">
            <div class="lotus-card-header-dark">
                Student User List
            </div>
            <div class="lotus-card-body-dark">
                <table>
                    <thead>
                        <tr>
                            <th style="width: 63px; border: 1px solid #636363;">ID</th>
                            <th style="width: 270px; border: 1px solid #636363;">Username</th>
                            <th style="width: 270px; border: 1px solid #636363;">Role</th>
                            <th style="width: 270px; border: 1px solid #636363;">Group</th>
                            <th style="width: 270px; border: 1px solid #636363;">Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for ea in student_list %}
                            {% if ea.student %} 
                                <tr>
                                    <td style="border: 1px solid #636363;"><a href="{% url 'lotus_user_student_details' ea.id %}" style="color: #aaa;">{{ ea.id }}</a></td>
                                    <td style="border: 1px solid #636363;">{{ ea.username }}</td>
                                    <td style="border: 1px solid #636363;">{{ea.student.role}}</td>
                                    <td style="border: 1px solid #636363;">{{ea.usergroup_set}}</td>
                                    <td style="border: 1px solid #636363;">{{ea.student}}</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>





{% endblock content %}

templates/lotus/pages/user/lotus_user_student_details.html
{% extends 'lotus/layout/base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="lotus-card-dark mb-3">
        <div class="lotus-card-header-dark">
            User Details
        </div>
        <div class="lotus-card-body-dark">
            <div class="card-body">
                <div class="row mt-2">
                    <div class="col-2 text-end" style="color: #aaa;">ID: </div>
                    <div class="col-10" style="color: #aaa;">{{details.id}}</div>
                </div>
                <div class="row mt-2">
                    <div class="col-2 text-end" style="color: #aaa;">Name: </div>
                    <div class="col-10" style="color: #aaa;">{% if details.employee %} {{details.employee}} {% elif details.student %} {{details.student}} {% endif %}</div>
                </div>
                <div class="row mt-2">
                    <div class="col-2 text-end" style="color: #aaa;">Role: </div>
                    <div class="col-10" style="color: #aaa;">{% if details.employee %} {{details.employee.role}} {% elif details.student %} {{details.student.role}} {% endif %}</div>
                </div>
                <div class="row mt-2">
                    <div class="col-2 text-end" style="color: #aaa;">Group: </div>
                    <div class="col-10" style="color: #aaa;">{{ details.usergroup }}</div>
                </div>
                
             
            </div>
        </div>
        <div class="lotus-card-header-dark">
            <div class="row">
                <div class="col text-end">
                    <a class="btn btn-sm btn-secondary py-0" href="" >Update</a>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}